#!/bin/sh
# demos for Grace
#

export GRACE_HOME
cd examples
# define the location
#
if test -x ../src/qtgrace
then
	GRACE=../src/qtgrace
	GRACE_HOME=`pwd`/..
fi

# don't ask stupid questions :)
#
#GRACE="../src/qtgrace"
GRACE="$GRACE"
#

# explain the row of single character buttons and a few other things
$GRACE $1
