.TH "grace" "1" "April 12, 2006" "" "Grace"
.SH "NAME"
grace \- command line interface
.br 
xmgrace \- full\-featured GUI mode
.br 
gracebat \- batch mode \- print and exit

.SH "SYNOPSIS"
.LP 
.B grace
.RI "[ " option " | " filename " ]..."
.br 
.B xmgrace
.RI "[ " option " | " filename " ]..."
.br 
.B gracebat
.RI "[ " option " | " filename " ]..."

.SH "DESCRIPTION"
Grace is a WYSIWYG tool to make two\-dimensional plots of scientific
data.
.SH "OPTIONS"
.TP 
.B "\-autoscale" "x|y|xy|none"
Set autoscale type
.TP 
.BI "\-barebones "
Turn off all toolbars
.TP 
.BI "\-block "    "file"               
Assume the data
.I file
is block data
.TP 
.BI "\-datehint "    "iso|european|us|days|seconds|nohint"              
Set the hint for dates analysis
.TP 
.BI "\-dpipe "    "descriptor"               
Read data from descriptor on startup
.TP 
.B \-free                                 
Use free page layout
.TP 
.B \-hardcopy
No interactive session, just print and quit
.TP 
.BI "\-hdevice "   "device_name"     
Set default hardcopy device
.TP 
.BI "\-hdevice\-options "   "option_string"     
Set options for default hardcopy device
.TP 
.B \-install
Install private colormap
.TP 
.B \-noask
Assume the answer is yes to all requests, if the operation would overwrite
a file, grace will do so without prompting
.TP 
.B \-noinstall                            
Don't use private colormap
.TP 
.B \-noprint                              
In batch mode, do not print
.TP 
.B \-nosafe                              
Disable safe mode
.TP 
.B \-nosigcatch                           
Don't catch signals
.TP 
.BI "\-npipe "     "file"                     
Read data from named pipe on startup
.TP 
.BI "\-nxy "       "file"
Assume data file is in X Y1 Y2 Y3 ...  format
.TP 
.BI "\-printfile " "file" 
Save print output to 
.I file 
.TP 
.BI "\-results "  "file"             
Write results of some data manipulations to 
.I file
.TP 
.B \-safe                              
Run in the safe mode (default)
.TP 
.BI "\-saveall "  "file"
Save all to 
.I file
.TP 
.BI "\-seed "     "value"               
Integer seed for random number generator
.TP 
.BI "\-timer "    "delay"                    
Set allowed time slice for real time inputs to
.I delay
ms
.TP 
.B \-settype   xy|xydx|...              
Set the type of the next data file
.TP 
.B \-version                             
Show the program version and exit
.TP 
.BI "\-wd "       "path"                
Set the working directory
.TP 
.B \-help
This message

.SH "RESOURCES"
When run in the GUI mode, the interface is a subject to X resource settings.
Please refer to the User's Guide for a list of important ones.

.SH "ENVIRONMENT"
.TP 
.B GRACE_HOME
Specifies the directory where the Grace docs and libs are stored. Default is
.BR /usr/local/grace
.TP 
.B GRACE_HELPVIEWER
The  shell command to run an HTML viewer for on\-line browsing of the help
documents. If includes an instance of "%s", it will be replaced with the actual
URL by Grace. Default is
.BR mozilla
.TP 
.B GRACE_EDITOR
Specifies the editor which is used to edit sets. Default is 
.B xterm \-e vi
.TP 
.B GRACE_PRINT_CMD
The print command.
.TP 
.B GRACE_FFTW_RAM_WISDOM
and
.B GRACE_FFTW_WISDOM_FILE
A flag (0 or 1) and a file name which determine whether a FFT should use 
`wisdom' when using the FFTW libraries.

.SH "FILES"
In many cases, when Grace needs to access a file given with a
relative \fBpathname\fR, it searches for the file along the
following path:
\fB./pathname:./.grace/pathname:~/.grace/pathname: $GRACE_HOME/pathname\fR

The following files are of a special importance:

\fBtemplates/Default.xgr\fR
\- the default template, loaded whenever a new project is started.

\fBfonts/FontDataBase\fR
\- the file responsible for font configuration.

.SH "SEE ALSO"
grconvert(1), X(1), Grace User's Guide

.SH "HOME PAGE"
http://plasma\-gate.weizmann.ac.il/Grace/

.SH "BUGS"
The best way to submit a bug report is using the "Help/Report an issue" menu
entry.  Alternatively, see the home page.

.SH "AUTHORS"
\fBGrace\fR is derived from \fBACE/gr\fR (a.k.a. \fBXmgr\fR) written by
Paul J Turner. From version number 4.00, the development was taken
over by a team of volunteers under the coordination of Evgeny Stambulchik.
As of now, most of the codebase has been re\-written from scratch.
.SH "COPYRIGHT"
Copyright (c) 1996\-2006 Grace Development Team
.br 
Portions Copyright (c) 1991\-1995 Paul J Turner, Portland, OR
.SH "LICENSE"
The program is distributed under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
