#!/bin/sh
# demos for Grace
#

export GRACE_HOME

# define the location
#
if test -x ../src/xmgrace
then
	GRACE=../src/xmgrace
	GRACE_HOME=`pwd`/..
else
if test -x ../bin/xmgrace
then
        GRACE=../bin/xmgrace
	GRACE_HOME=`pwd`/..
else
	GRACE=xmgrace
fi
fi

# don't ask stupid questions :)
#
GRACE="$GRACE -noask"
#

#
# new xgr project
$GRACE diode.xgr
#

# explain the row of single character buttons and a few other things
$GRACE explain.agr 
#
# display the various axes available
$GRACE axes.agr 
#
# display the symbols and line styles
$GRACE symslines.agr 
#
# display various fill styles
$GRACE fills.agr 
#
# some graph stuff and ticks
$GRACE props.agr 
#
# demonstration of many graphs
$GRACE manygraphs.agr
#
# test of a graph inset
$GRACE tinset.agr
#
# some time and date formats
$GRACE times.agr 
#
# Australia map
$GRACE au.agr 
#
# more log plots
$GRACE tlog.agr 
#
# a log2 example
$GRACE log2.agr 
#
# a logit scale sample
$GRACE logit.agr 
#
# a reciprocal scale sample
$GRACE reciprocal.agr 
#
# display fonts and font mappings
$GRACE tfonts.agr 
#
# text transforms
$GRACE txttrans.agr 
#
# advaned typesetting
$GRACE typeset.agr
#
$GRACE test2.agr 
#
# explanation of arrow shape parameters
$GRACE arrows.agr 
#
# multiple graphs created with arrange feature
$GRACE co2.agr 
#
# a nice sample
$GRACE spectrum.agr 
#
# a graph with error bars
$GRACE terr.agr
#
# a fixed graph with XY RADIUS format
$GRACE txyr.agr 
#
# string annotations
$GRACE motif.agr 
#
# a graph with an XYZ set
$GRACE xyz.agr 
#
# a graph with HILO data
$GRACE hilo.agr 
#
# a graph with BOXPLOT data
$GRACE boxplot.agr 
#
# polar plots
$GRACE polar.agr
#
# bar charts
#
# a bar graph demonstrating specified ticks and tick labels
$GRACE bar.agr
#
# a stacked bar chart
$GRACE stackedb.agr
#
# a bar chart with error bars
$GRACE chartebar.agr
#
# display all types of XY charts
$GRACE charts.agr
#
# pie charts
$GRACE pie.agr
#
# vector map
$GRACE vmap.agr
#
# a bubble plot
$GRACE xysize.agr
#
# an xycolor map
$GRACE xycolor.agr
#
# non-linear curve fitting
#$GRACE logistic.agr
#
