#!/bin/sh
PATH=/bin:/usr/bin:/usr/local/bin
export PATH

cat << EOF > Make.conf
YACC=bison -y
EOF

make configure
make CHANGES
CDIR=`pwd`
CDIR_BNAME=`basename $CDIR`
cd src
make pars.c
cd ..
cd doc
make all
cd ..
rm -f Make.conf
cd ..
tar --exclude \*CVS\* -cvzf ${CDIR_BNAME}.tar.gz $CDIR_BNAME
cd -
