#!/bin/sh
PATH=/bin:/usr/bin:/usr/local/bin
export PATH

make configure

cat << EOF > Make.conf
.SUFFIXES:
O=.o
EXE=
YACC=bison -y
XCC=xcc
EOF

make NEWS
make ChangeLog

CDIR=`pwd`
CDIR_BNAME=`basename $CDIR`
cd src
touch Make.dep
make pars.c
make xml_in.c
rm -f Make.dep
cd ..
cd doc
make all
cd ..
rm -f Make.conf
cd ..
tar --exclude \*CVS\* --exclude .cvsignore -cvzf ${CDIR_BNAME}.tar.gz $CDIR_BNAME
cd -
